### ISSUE TITLE
KeyError: 'up_cross'

### ISSUE THREAD

**Issue by one-zd** [sen-mao/SuppressEOT#1]
RUN : python suppress_eot_w_nulltext.py  --type Real-Image \
                                   --prompt "A man with a beard wearing glasses and a hat in blue shirt" \
                                   --image_path "./example_images/A man with a beard wearing glasses and a hat in blue shirt.jpg" \
                                   --token_indices "[[4,5],[7],[9,10],]" \
                                   --alpha "[1.,]" --cross_retain_steps "[.2,]"

ERROR: Traceback (most recent call last):
  File "E:\code\SuppressEOT-master\suppress_eot_w_nulltext.py", line 459, in <module>
    main(args, stable)
  File "E:\code\SuppressEOT-master\suppress_eot_w_nulltext.py", line 414, in main
    image_inv, x_t = run_and_display(stable, [prompt], controller, latent=x_t, uncond_embeddings=uncond_embeddings, verbose=False)
  File "E:\code\SuppressEOT-master\suppress_eot_w_nulltext.py", line 336, in run_and_display
    images, x_t = text2image_ldm_stable(ldm_stable, prompts, controller, latent=latent,
  File "C:\Users\anaconda3\envs\eot\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "E:\code\SuppressEOT-master\suppress_eot_w_nulltext.py", line 277, in text2image_ldm_stable
    attention_maps = aggregate_attention(controller, 16, ["up", "down"], is_cross=True)
  File "E:\code\SuppressEOT-master\suppress_eot_w_nulltext.py", line 151, in aggregate_attention
    for item in attention_maps[f"{location}_{'cross' if is_cross else 'self'}"]:
KeyError: 'up_cross'

Windows11，I debug the code and find that attention_maps is empty, may I ask how to correct it? Looking forward to your reply, thank you very much!

**Comment by sen-mao** [comment]
This issue is usually caused by the version of diffusers. Please refer to https://github.com/google/prompt-to-prompt/issues/57#issuecomment-1613729431 and try installing the latest version. In my experience, installing diffusers version 0.17.1 or newer should resolve the issue, as the Attention class has been rewritten.

**Comment by one-zd** [comment]
Thank you very much for your reply. According to your answer, the problem has been successfully solved.

**Comment by one-zd** [comment]
> This issue is usually caused by the version of diffusers. Please refer to [google/prompt-to-prompt#57 (comment)](https://github.com/google/prompt-to-prompt/issues/57#issuecomment-1613729431) and try installing the latest version. In my experience, installing diffusers version 0.17.1 or newer should resolve the issue, as the Attention class has been rewritten.

Thank you very much for your reply. According to your answer, the problem has been successfully solved

**Comment by one-zd** [comment]
大佬，请问可以加个微信吗？我也是国内985在读博士生

**Comment by sen-mao** [comment]
Can you provide me with your WeChat number? Or we can connect through email (senmaonk@gmail.com).

**Comment by one-zd** [comment]
> Can you provide me with your WeChat number? Or we can connect through email ([senmaonk@gmail.com](mailto:senmaonk@gmail.com)).Okay, thanks. For your privacy, I will delete conversations that have nothing to do with the question.
