### ISSUE TITLE
How can I suppress objects in generated images?

### ISSUE THREAD

**Issue by ZichengDuan** [sen-mao/SuppressEOT#2]
Hi Senmao, thanks for providing the code of your great work, it's really impressive and inspiring. I wonder if you can provide some instructions on how to suppress the objects or object semantics during the image generation process as in paper figure 10(b)? Thanks for your help!

**Comment by sen-mao** [comment]
Figure 10 does not seem to have (b).

1. Please refer to "**Suppression for generated image**" in the README for suppression semantics (e.g., Monet style or ID) for generation images.

2. Please refer to "**Suppression for real image**" in the README, replacing the type 'Real-Image' with 'Generated-Image' for suppressing objects in generated images
